// 桌面 exe 运行在 file:// 下，因此 API 使用部署站点的绝对地址。
// 本地联调时可改为 http://127.0.0.1:8080/api。
const API = 'https://ucloud-dev3.1-url.cn/api';
const state={token:localStorage.getItem('fh_token'),user:JSON.parse(localStorage.getItem('fh_user')||'null'),lastId:0,poll:null};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function linkify(s){return esc(s).replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>')}
function bytes(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';if(n<1073741824)return (n/1048576).toFixed(1)+' MB';return (n/1073741824).toFixed(1)+' GB'}
function fileUrl(id){return API+'/files.php?id='+id+'&token='+encodeURIComponent(state.token)}
function showChat(){ $('loginView').classList.add('hidden');$('chatView').classList.remove('hidden');const name=state.user?.username||'';$('accountLabel').textContent=name;$('userBadge').textContent=name.slice(0,1).toUpperCase(); load(true); if(state.poll)clearInterval(state.poll);state.poll=setInterval(()=>load(false),3000)}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+state.token};const r=await fetch(API+path,opt);const d=await r.json().catch(()=>({error:'服务器返回异常'}));if(!r.ok)throw Error(d.error||'请求失败');return d}
async function auth(action){const d=await fetch(API+'/auth.php?action='+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});const j=await d.json();if(!d.ok)throw Error(j.error);state.token=j.token;state.user=j.user;localStorage.setItem('fh_token',state.token);localStorage.setItem('fh_user',JSON.stringify(state.user));showChat()}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authError').textContent='';try{await auth('login')}catch(x){$('authError').textContent=x.message}};
$('registerBtn').onclick=async()=>{try{await auth('register')}catch(x){$('authError').textContent=x.message}};
$('logoutBtn').onclick=()=>{localStorage.clear();location.reload()};
function render(m){const row=document.createElement('div');row.className='message';let content='';if(m.message_type==='text')content='<div class="bubble">'+linkify(m.body)+'</div>';else if(m.message_type==='image')content='<a class="bubble imageBubble" href="'+fileUrl(m.attachment_id)+'" target="_blank" rel="noopener"><img class="imagePreview" src="'+fileUrl(m.attachment_id)+'" alt="图片预览" loading="lazy"></a>';else{const icon=m.message_type==='video'?'🎬':'📎';content='<a class="bubble fileCard" href="'+fileUrl(m.attachment_id)+'" target="_blank"><span class="fileIcon">'+icon+'</span><span><div class="fileName">'+esc(m.original_name)+'</div><div class="fileSize">'+bytes(Number(m.size_bytes))+' · 点击打开</div></span></a>'}row.innerHTML=content+'<div class="meta">'+new Date(m.created_at.replace(' ','T')+'Z').toLocaleString()+'</div>';$('messages').append(row);state.lastId=Math.max(state.lastId,Number(m.id))}
async function load(initial){try{const d=await api('/messages.php?after='+(initial?0:state.lastId));if(initial)$('messages').innerHTML='';d.messages.forEach(render);$('syncStatus').textContent='已同步';$('recordCount').textContent=state.lastId||'0';if(d.messages.length)$('messages').scrollTop=$('messages').scrollHeight}catch(e){$('syncStatus').textContent='连接异常'}}
async function sendText(){const el=$('textInput'),body=el.value.trim();if(!body)return;el.value='';try{await api('/messages.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body,message_type:'text'})});await load(false)}catch(e){alert(e.message)}}
$('composer').onsubmit=e=>{e.preventDefault();sendText()};
$('textInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.ctrlKey){e.preventDefault();sendText()}});
async function upload(files){for(const file of files){if(!confirm('是否发送“'+file.name+'”？'))continue;const fd=new FormData();fd.append('file',file);try{await api('/upload.php',{method:'POST',body:fd});await load(false)}catch(e){alert(e.message)}}}
$('fileInput').onchange=e=>{upload([...e.target.files]);e.target.value=''};document.addEventListener('dragover',e=>{e.preventDefault();$('chatView').classList.add('dragging')});document.addEventListener('dragleave',e=>{if(e.clientX<=0||e.clientY<=0)$('chatView').classList.remove('dragging')});document.addEventListener('drop',e=>{e.preventDefault();$('chatView').classList.remove('dragging');if(e.dataTransfer.files.length)upload([...e.dataTransfer.files])});
if(state.token&&state.user)showChat();
